baseurl = "https://hanneskuchelmeister.de/"
title = "Kuchelmeister"

theme = "hugo-coder-timeline"

languagecode = "en-uk"
defaultcontentlanguage = "en-uk"

paginate = 30
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
    enableRSS = true

    author = "Hannes F. Kuchelmeister"
    description = "Hannes F. Kuchelmeister's personal website"
    keywords = "blog,developer,personal"
    info = "Master's Student in Computer Science at Uppsala University"
    avatarurl = "images/avatar.jpg"
    footercontent = ""

    dateformat = "2 January, 2006"

    hideCredits = true
    hideCopyright = false
    since = 2020
    # Git Commit in Footer, uncomment the line below to enable it.

    rtl = false

    # Specify light/dark colorscheme
    # Supported values:
    # "auto" (use preference set by browser)
    # "dark" (dark background, light foreground)
    # "light" (light background, dark foreground) (default)
    colorscheme = "auto"

    # Custom CSS
    custom_css = []

    # Custom JS
    custom_js = []

# If you want to use fathom(https://usefathom.com) for analytics, add this section
#[params.fathomAnalytics]


[[params.social]]
    name = "Github"
    icon = "fa fa-github"
    weight = 1
    url = "https://github.com/13hannes11/"
[[params.social]]
    name = "E-Mail"
    icon = "fa fa-envelope"
    weight = 2
    url = "mailto://hanneskuchelmeister.de"
[[params.social]]
    name = "PGP-Key"
    icon = "fa fa-lock"
    weight = 3
    url = "http://keys.gnupg.net/pks/lookup?search=0x79E6AC8794C85FA90CF00AF05923AEAB59ABFFB0&fingerprint=on&op=index"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 4
    url = "https://www.linkedin.com/in/hannes-kuchelmeister/"
[[params.social]]
    name = "RSS"
    icon = "fas fa-rss"
    weight = 6
    url = "index.xml"
    rel = "alternate"
    type = "application/rss+xml"
[taxonomies]
    category = "categories"
    series = "series"
    tag = "tags"

[[menu.main]]
    name = "Home"
    weight = 1
    url = "/"  
[[menu.main]]
    name = "Programming Languages"
    weight = 2
    url = "languages/"




