# baseurl = "https://hanneskuchelmeister.de/"
title = "Kuchelmeister"

theme = "hugo-coder-timeline"

languagecode = "en-uk"
defaultcontentlanguage = "en-uk"

paginate = 30
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true



[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    disable = true
  [privacy.instagram]
    disable = true
  [privacy.twitter]
    disable = true
  [privacy.vimeo]
    disable = true
  [privacy.youtube]
    disable = false
    privacyEnhanced = true



[params]
    enableRSS = true

    author = "Hannes F. Kuchelmeister"
    description = "Hannes F. Kuchelmeister's personal website"
    keywords = "blog,developer,personal,rust,foss"
    info = "Software Engineer and Open Source Enthusiast"
    avatarurl = "/images/avatar.avif"
    footercontent = ""

    dateformat = "2 January, 2006"

    hideCredits = true
    hideCopyright = false
    since = 2020
    # Git Commit in Footer, uncomment the line below to enable it.

    rtl = false

    # Specify light/dark colorscheme
    # Supported values:
    # "auto" (use preference set by browser)
    # "dark" (dark background, light foreground)
    # "light" (light background, dark foreground) (default)
    colorscheme = "auto"

    # Custom CSS
    custom_css = []

    # Custom JS
    custom_js = []
    
    timelineTitle="Projects"
    timelineType="posts"

# If you want to use fathom(https://usefathom.com) for analytics, add this section
#[params.fathomAnalytics]


[[params.social]]
    name = "Github"
    icon = "fa fa-2x fa-github"
    weight = 1
    url = "https://github.com/13hannes11/"
[[params.social]]
    name = "Matrix"
    icon = "fa fa-2x fa-matrix-org"
    weight = 1
    url = "https://matrix.to/#/@hannes:kuchelmeister.org"
[[params.social]]
    name = "E-Mail"
    icon = "fa fa-2x fa-envelope"
    weight = 2
    url = "mailto://hannes@kuchelmeister.org"
[[params.social]]
    name = "LinkedIn"
    icon = "fa fa-2x fa-linkedin"
    weight = 4
    url = "https://www.linkedin.com/in/hannes-kuchelmeister/"
[[params.social]]
    name = "RSS"
    icon = "fa fa-2x fa-rss"
    weight = 6
    url = "index.xml"
    rel = "alternate"
    type = "application/rss+xml"

[taxonomies]
    category = "categories"
    series = "series"
    tag = "tags"

[[menu.main]]
    name = "Home"
    weight = 1
    url = "/"  
[[menu.main]]
    name = "Programming Languages"
    weight = 2
    url = "languages/"




